name = "ai-chatbot"
pages_build_output_dir = "dist"

compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "ai-chatbot-db"
database_id = ""

[[env.production]]
vars = { TOKENLB_KEY = "", BLUESMINDS_KEY = "" }
